// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/daymenu/gostudy/examples/wire/basics/foobarbaz"
)

// Injectors from wire.go:

func initializeBaz(ctx context.Context) (foobarbaz.Baz, error) {
	foo := foobarbaz.ProvideFoo()
	bar := foobarbaz.ProvideBar(foo)
	baz, err := foobarbaz.ProvideBaz(ctx, bar)
	if err != nil {
		return foobarbaz.Baz{}, err
	}
	return baz, nil
}

func initializeBar(ctx context.Context) (foobarbaz.Bar, error) {
	foo := foobarbaz.ProvideFoo()
	bar := foobarbaz.ProvideBar(foo)
	return bar, nil
}

func initializeFoo(ctx context.Context) (foobarbaz.Foo, error) {
	foo := foobarbaz.ProvideFoo()
	return foo, nil
}
